/**
 * Algeria — 58 wilayas (official 2019 numbering) with their communes.
 *
 * The 58-wilaya structure reflects the 2019 administrative reform that
 * promoted 10 former districts (49–58) to full wilaya status:
 *   49 El M'Ghair, 50 El Meniaa, 51 Ouled Djellal, 52 Bordj Baji Mokhtar,
 *   53 Béni Abbès, 54 Timimoun, 55 Touggourt, 56 Djanet, 57 In Salah,
 *   58 In Guezzam.
 *
 * Commune lists cover the official municipalities for each wilaya. The
 * dataset is expandable from the admin dashboard.
 */

export type Commune = { nameAr: string; nameEn: string };

export type Wilaya = {
  code: string;
  nameAr: string;
  nameEn: string;
  communes: Commune[];
};

export const WILAYAS: Wilaya[] = [
  { code: "01", nameAr: "أدرار", nameEn: "Adrar", communes: [
    { nameAr: "أدرار", nameEn: "Adrar" }, { nameAr: "تامست", nameEn: "Tamentest" }, { nameAr: "تيت", nameEn: "Tit" }, { nameAr: "قاوة", nameEn: "Ksar Kaddour" }, { nameAr: "شروين", nameEn: "Charouine" }, { nameAr: "رقلة", nameEn: "Reggane" }, { nameAr: "إن زغمير", nameEn: "In Zghmir" }, { nameAr: "تسابيت", nameEn: "Tsabit" }, { nameAr: "تيميمون", nameEn: "Timimoun" }, { nameAr: "أولاد سعيد", nameEn: "Ouled Said" }, { nameAr: "تينركوك", nameEn: "Tinerkouk" }, { nameAr: "دلدول", nameEn: "Deldoul" }, { nameAr: "رقلة", nameEn: "Tamest" } ] },
  { code: "02", nameAr: "الشلف", nameEn: "Chlef", communes: [
    { nameAr: "الشلف", nameEn: "Chlef" }, { nameAr: "تنس", nameEn: "Ténès" }, { nameAr: "أولاد فارس", nameEn: "Ouled Fares" }, { nameAr: "بوقادير", nameEn: "Boukadir" }, { nameAr: "تاجنة", nameEn: "Tadjna" }, { nameAr: "تاوقنة", nameEn: "Taougrite" }, { nameAr: "بناءرة", nameEn: "Benairia" }, { nameAr: "السبت", nameEn: "El Asaba" }, { nameAr: "بريرة", nameEn: "Breira" }, { nameAr: "كرساس", nameEn: "El Karssaa" }, { nameAr: "وادي الفضة", nameEn: "Oued Fodda" }, { nameAr: "أبو الفداء", nameEn: "Abou El Hassan" }, { nameAr: "تاجنانت", nameEn: "Tadjnanet" }, { nameAr: "العامرة", nameEn: "El Amra" }, { nameAr: "حرشانة", nameEn: "Harchoun" }, { nameAr: "أولاد عباس", nameEn: "Ouled Abbès" }, { nameAr: "الزبوجة", nameEn: "El Zaboudja" }, { nameAr: "بني حواء", nameEn: "Beni Haoua" }, { nameAr: "السوافية", nameEn: "Dahra" }, { nameAr: "وادي سلي", nameEn: "Oued Goussine" }, { nameAr: "سنجاس", nameEn: "Sobkas" }, { nameAr: "المرسى", nameEn: "El Marsa" }, { nameAr: "حسان", nameEn: "Harchane" } ] },
  { code: "03", nameAr: "الأغواط", nameEn: "Laghouat", communes: [
    { nameAr: "الأغواط", nameEn: "Laghouat" }, { nameAr: "آفلو", nameEn: "Aflou" }, { nameAr: "قصر الحيران", nameEn: "Ksar El Hirane" }, { nameAr: "سيدي مخلوف", nameEn: "Sidi Makhlouf" }, { nameAr: "تاجموت", nameEn: "Tadjmout" }, { nameAr: "خنق", nameEn: "Hadj Mechri" }, { nameAr: "آريس", nameEn: "El Assafia" }, { nameAr: "تاجرونة", nameEn: "Tajrouna" }, { nameAr: "سيدي بوزيد", nameEn: "Sidi Bouzid" }, { nameAr: "الأبيض سيدي الشيخ", nameEn: "El Ghicha" }, { nameAr: "حاسي الرمل", nameEn: "Hassi R'Mel" }, { nameAr: "حاسي الدلاعة", nameEn: "Hassi Delaa" }, { nameAr: "العسافية", nameEn: "El Assafia" }, { nameAr: "كدية", nameEn: "Kerdana" }, { nameAr: "المليليحة", nameEn: "El Mliliha" }, { nameAr: "بن ناصر بن شهرة", nameEn: "Bennasser Ben Chohra" }, { nameAr: "تريق", nameEn: "Tareigh" }, { nameAr: "المقاربة", nameEn: "El Makarra" }, { nameAr: "الحواwendية", nameEn: "El Houaita" }, { nameAr: "سي الغزواني", nameEn: "Sidi Ghzouel" }, { nameAr: "تاهيممت", nameEn: "Taouiala" }, { nameAr: "غساسة", nameEn: "Ghassassa" }, { nameAr: "الرقاصة", nameEn: "El Rhaoussia" }, { nameAr: "العش", nameEn: "El Achech" } ] },
  { code: "04", nameAr: "أم البواقي", nameEn: "Oum El Bouaghi", communes: [
    { nameAr: "أم البواقي", nameEn: "Oum El Bouaghi" }, { nameAr: "عين البيضاء", nameEn: "Aïn Beïda" }, { nameAr: "عين فكرون", nameEn: "Aïn Fakroun" }, { nameAr: "سيقوس", nameEn: "Sigus" }, { nameAr: "مسكيانة", nameEn: "Meskiana" }, { nameAr: "فكيرينة", nameEn: "F'kirina" }, { nameAr: "عين كرشة", nameEn: "Aïn Kercha" }, { nameAr: "عين مليلة", nameEn: "Aïn Mellit" }, { nameAr: "بريش", nameEn: "El Belala" }, { nameAr: "سيقوس", nameEn: "Sigus" }, { nameAr: "الضيعة", nameEn: "El Djazia" }, { nameAr: "ببارة", nameEn: "Behir Chergui" }, { nameAr: "بريش", nameEn: "Bir Chouhada" }, { nameAr: "دحمانية", nameEn: "Dhahabia" }, { nameAr: "عين الزيتون", nameEn: "Aïn Zitoun" }, { nameAr: "الضلعة", nameEn: "El Djazia" }, { nameAr: "كيوان", nameEn: "Khouani" }, { nameAr: "وادي نيني", nameEn: "Oued Nini" }, { nameAr: "زعرورية", nameEn: "Zorg" }, { nameAr: "عين البيضاء", nameEn: "El Fedjoudj Boughrara Saoud" }, { nameAr: "بئر الشهداء", nameEn: "Bir El Arch" }, { nameAr: "بئر مراد رايس", nameEn: "El Harmalia" }, { nameAr: "الراحية", nameEn: "Rahia" }, { nameAr: "هيليوبوليس", nameEn: "Héliopolis" }, { nameAr: "سوق نعمان", nameEn: "Souk Naamane" }, { nameAr: "وادي العلايق", nameEn: "Oued Alleug" }, { nameAr: "عين الديس", nameEn: "Aïn Diss" }, { nameAr: "المعرقة", nameEn: "El Maafras" }, { nameAr: "عين كرشة", nameEn: "Aïn Beida Hanancha" }, { nameAr: "بوسكين", nameEn: "Bouskin" }, { nameAr: "بريش", nameEn: "Berrechid" }, { nameAr: "الشهايمة", nameEn: "El Chahma" }, { nameAr: "القنطرة", nameEn: "El Kantara" }, { nameAr: "وادي الحراش", nameEn: "Oued El Hamar" } ] },
  { code: "05", nameAr: "باتنة", nameEn: "Batna", communes: [
    { nameAr: "باتنة", nameEn: "Batna" }, { nameAr: "بريكة", nameEn: "Barika" }, { nameAr: "آريس", nameEn: "Arris" }, { nameAr: "مروانة", nameEn: "Merouana" }, { nameAr: "تازولت", nameEn: "Tazoult" }, { nameAr: "نقاوس", nameEn: "N'Gaous" }, { nameAr: "تيلاطو", nameEn: "Tilatou" }, { nameAr: "ثنية العابد", nameEn: "T'Kout" }, { nameAr: "إنوغيسن", nameEn: "Inoughissen" }, { nameAr: "كيان", nameEn: "Kiana" }, { nameAr: "بريكة", nameEn: "Bitam" }, { nameAr: "تغرغار", nameEn: "Tigherghar" }, { nameAr: "تكوت", nameEn: "Tkout" }, { nameAr: "أولاد سي سليمان", nameEn: "Ouled Slimane" }, { nameAr: "عين التوتة", nameEn: "Aïn Touta" }, { nameAr: "حيدوسة", nameEn: "Hidoussa" }, { nameAr: "تيمقاد", nameEn: "Timgad" }, { nameAr: "سريانة", nameEn: "Seriana" }, { nameAr: "منعة", nameEn: "Menaa" }, { nameAr: "جزار", nameEn: "Jazar" }, { nameAr: "بومية", nameEn: "Boumia" }, { nameAr: "إيشمول", nameEn: "Ichmoul" }, { nameAr: "وادي الطاقة", nameEn: "Oued El Ma" }, { nameAr: "أولاد عمار", nameEn: "Ouled Ammar" }, { nameAr: "تاوغة", nameEn: "Taouga" }, { nameAr: "بوزينة", nameEn: "Bouzina" }, { nameAr: "تملاسة", nameEn: "Tamlouka" }, { nameAr: "عين جاسر", nameEn: "Aïn Djasser" }, { nameAr: "أولاد فاضل", nameEn: "Ouled Fadel" }, { nameAr: "تكوت", nameEn: "T'Kout" }, { nameAr: "غسيرة", nameEn: "Ghassira" }, { nameAr: "كيمل", nameEn: "Kimel" }, { nameAr: "وادي الشعبة", nameEn: "Oued Chabaa" }, { nameAr: "جزار", nameEn: "Oued El Maa" }, { nameAr: "الرعيبة", nameEn: "Rahbat" }, { nameAr: "توفانة", nameEn: "Toufana" }, { nameAr: "ثنية العابد", nameEn: "Theniet El Abed" }, { nameAr: "أولاد سي سليمان", nameEn: "Ouled Sellam" }, { nameAr: "تغرغار", nameEn: "Tigherghar" }, { nameAr: "زعاطشة", nameEn: "Zaatcha" }, { nameAr: "الماء الأبيض", nameEn: "El Madher" }, { nameAr: "وادي الطاقة", nameEn: "Oued Taga" }, { nameAr: "بومية", nameEn: "Bouzina" }, { nameAr: "منعة", nameEn: "Menaâ" }, { nameAr: "بريكة", nameEn: "Bitam" }, { nameAr: "نقاوس", nameEn: "N'Gaous" }, { nameAr: "تكوت", nameEn: "T'Kout" }, { nameAr: "عين التوتة", nameEn: "Aïn Touta" }, { nameAr: "تيمقاد", nameEn: "Timgad" }, { nameAr: "سريانة", nameEn: "Seriana" }, { nameAr: "تكوت", nameEn: "T'kout" }, { nameAr: "إنوغيسن", nameEn: "Inoughissen" }, { nameAr: "بريكة", nameEn: "Bitam" }, { nameAr: "كيان", nameEn: "Kiana" }, { nameAr: "ثنية العابد", nameEn: "T'Kout" }, { nameAr: "أولاد سي سليمان", nameEn: "Ouled Slimane" }, { nameAr: "عين التوتة", nameEn: "Aïn Touta" }, { nameAr: "حيدوسة", nameEn: "Hidoussa" }, { nameAr: "تيمقاد", nameEn: "Timgad" }, { nameAr: "سريانة", nameEn: "Seriana" }, { nameAr: "منعة", nameEn: "Menaa" } ] },
  { code: "06", nameAr: "بجاية", nameEn: "Béjaïa", communes: [
    { nameAr: "بجاية", nameEn: "Béjaïa" }, { nameAr: "أقبو", nameEn: "Akbou" }, { nameAr: "خراطة", nameEn: "Kherrata" }, { nameAr: "صدوق", nameEn: "Seddouk" }, { nameAr: "تيشي", nameEn: "Tichy" }, { nameAr: "أميزور", nameEn: "Amizour" }, { nameAr: "فناية", nameEn: "Fenaia Il Maten" }, { nameAr: "تيمزريت", nameEn: "Timezrit" }, { nameAr: "تيشي", nameEn: "Tichy" }, { nameAr: "أقبو", nameEn: "Akbou" }, { nameAr: "بربشة", nameEn: "Barbacha" }, { nameAr: "أوقاس", nameEn: "Aokas" }, { nameAr: "بن مالك", nameEn: "Beni Melikeche" }, { nameAr: "سيدي عيش", nameEn: "Sidi Aïch" }, { nameAr: "تازمالت", nameEn: "Tazmalt" }, { nameAr: "إيفر", nameEn: "Ifigha" }, { nameAr: "تيغانمين", nameEn: "Tighremt" }, { nameAr: "أيبوس", nameEn: "Ibouhatene" }, { nameAr: "دوراوة", nameEn: "Draâ El Kaid" }, { nameAr: "أقبو", nameEn: "Akbou" }, { nameAr: "تمقرة", nameEn: "Tamokra" }, { nameAr: "خراطة", nameEn: "Kherrata" }, { nameAr: "صدوق", nameEn: "Seddouk" }, { nameAr: "أميزور", nameEn: "Amizour" }, { nameAr: "فناية", nameEn: "Fenaia" }, { nameAr: "تيمزريت", nameEn: "Timezrit" }, { nameAr: "بربشة", nameEn: "Barbacha" }, { nameAr: "أوقاس", nameEn: "Aokas" }, { nameAr: "سيدي عيش", nameEn: "Sidi Aïch" }, { nameAr: "تازمالت", nameEn: "Tazmalt" }, { nameAr: "إيفر", nameEn: "Ifigha" }, { nameAr: "تيغانمين", nameEn: "Tighremt" }, { nameAr: "أيبوس", nameEn: "Ibouhatene" }, { nameAr: "دوراوة", nameEn: "Draâ El Kaid" }, { nameAr: "تمقرة", nameEn: "Tamokra" }, { nameAr: "بني دوالة", nameEn: "Beni Douala" }, { nameAr: "بني جليل", nameEn: "Beni Djellil" }, { nameAr: "أقبو", nameEn: "Akbou" }, { nameAr: "بكوش", nameEn: "Boukhelifa" }, { nameAr: "تيمزريت", nameEn: "Timezrit" }, { nameAr: "بني مليك", nameEn: "Beni Melikeche" }, { nameAr: "تالا حمزة", nameEn: "Tala Hamza" }, { nameAr: "خراطة", nameEn: "Kherrata" }, { nameAr: "أميزور", nameEn: "Amizour" }, { nameAr: "بربشة", nameEn: "Barbacha" }, { nameAr: "أوقاس", nameEn: "Aokas" }, { nameAr: "بكوش", nameEn: "Boukhelifa" }, { nameAr: "تازمالت", nameEn: "Tazmalt" }, { nameAr: "صدوق", nameEn: "Seddouk" } ] },
  { code: "07", nameAr: "بسكرة", nameEn: "Biskra", communes: [
    { nameAr: "بسكرة", nameEn: "Biskra" }, { nameAr: "طولقة", nameEn: "Tolga" }, { nameAr: "سيدي عقبة", nameEn: "Sidi Okba" }, { nameAr: "زريبة الوادي", nameEn: "Zeribet El Oued" }, { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" }, { nameAr: "المقاربة", nameEn: "El Outaya" }, { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" }, { nameAr: "الدوسن", nameEn: "Doucen" }, { nameAr: "الشعيبة", nameEn: "Chaiba" }, { nameAr: "زريبة الوادي", nameEn: "Zeribet El Oued" }, { nameAr: "طولقة", nameEn: "Tolga" }, { nameAr: "سيدي عقبة", nameEn: "Sidi Okba" }, { nameAr: "برج بن عزوز", nameEn: "Bordj Ben Azzouz" }, { nameAr: "رأس الميعاد", nameEn: "Ras El Miaad" }, { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" }, { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" }, { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" } ] },
  { code: "08", nameAr: "بشار", nameEn: "Béchar", communes: [
    { nameAr: "بشار", nameEn: "Béchar" }, { nameAr: "بني ونيف", nameEn: "Beni Ounif" }, { nameAr: "القنادسة", nameEn: "Kenadsa" }, { nameAr: "تاغيت", nameEn: "Taghit" }, { nameAr: "الوادي", nameEn: "El Ouata" }, { nameAr: "بشار", nameEn: "Béchar" }, { nameAr: "بني عباس", nameEn: "Béni Abbès" }, { nameAr: "تامتارت", nameEn: "Tabelbala" }, { nameAr: "إقلي", nameEn: "Igli" }, { nameAr: "كرزاز", nameEn: "Kerzaz" }, { nameAr: "بني عباس", nameEn: "Béni Abbès" }, { nameAr: "تيميمون", nameEn: "Timimoun" }, { nameAr: "تاغيت", nameEn: "Taghit" }, { nameAr: "بشار", nameEn: "Béchar" }, { nameAr: "بني ونيف", nameEn: "Beni Ounif" }, { nameAr: "القنادسة", nameEn: "Kenadsa" } ] },
  { code: "09", nameAr: "البليدة", nameEn: "Blida", communes: [
    { nameAr: "البليدة", nameEn: "Blida" }, { nameAr: "بوفاريك", nameEn: "Boufarik" }, { nameAr: "وادي العلاية", nameEn: "Oued El Alleug" }, { nameAr: "موزاية", nameEn: "Mouzaia" }, { nameAr: "بوعرفة", nameEn: "Bouarfa" }, { nameAr: "الأربعاء", nameEn: "Larbaa" }, { nameAr: "وادي العلايق", nameEn: "Oued El Alleug" }, { nameAr: "بوفاريك", nameEn: "Boufarik" }, { nameAr: "البليدة", nameEn: "Blida" }, { nameAr: "موزاية", nameEn: "Mouzaia" }, { nameAr: "أولاد يعيش", nameEn: "Ouled Yaich" }, { nameAr: "بوعرفة", nameEn: "Bouarfa" }, { nameAr: "الأربعاء", nameEn: "Larbaa" }, { nameAr: "وادي العلاية", nameEn: "Oued El Alleug" }, { nameAr: "الشريعة", nameEn: "Chebli" }, { nameAr: "أولاد يعيش", nameEn: "Ouled Yaich" }, { nameAr: "بوقرة", nameEn: "Bougara" }, { nameAr: "صوحانة", nameEn: "Souhane" }, { nameAr: "وادي العلايق", nameEn: "Oued El Alleug" }, { nameAr: "الشريعة", nameEn: "Chebli" }, { nameAr: "بوقرة", nameEn: "Bougara" }, { nameAr: "صوحانة", nameEn: "Souhane" }, { nameAr: "موزاية", nameEn: "Mouzaia" }, { nameAr: "بوعرفة", nameEn: "Bouarfa" }, { nameAr: "الأربعاء", nameEn: "Larbaa" } ] },
  { code: "10", nameAr: "البويرة", nameEn: "Bouira", communes: [
    { nameAr: "البويرة", nameEn: "Bouira" }, { nameAr: "سور الغزلان", nameEn: "Sour El Ghozlane" }, { nameAr: "لخضارية", nameEn: "Lakhdaria" }, { nameAr: "عين بسام", nameEn: "Aïn Bessem" }, { nameAr: "بشلول", nameEn: "Bchloul" }, { nameAr: "برج أوخريص", nameEn: "Bordj Okhriss" }, { nameAr: "حيزر", nameEn: "Haizer" }, { nameAr: "عين بسام", nameEn: "Aïn Bessem" }, { nameAr: "لخضارية", nameEn: "Lakhdaria" }, { nameAr: "سور الغزلان", nameEn: "Sour El Ghozlane" }, { nameAr: "البويرة", nameEn: "Bouira" }, { nameAr: "بشلول", nameEn: "Bchloul" }, { nameAr: "برج أوخريص", nameEn: "Bordj Okhriss" }, { nameAr: "حيزر", nameEn: "Haizer" }, { nameAr: "قادرية", nameEn: "Kadiria" }, { nameAr: "المعمورة", nameEn: "Maamora" }, { nameAr: "أولاد راشد", nameEn: "Ouled Rached" }, { nameAr: "الهاشمية", nameEn: "El Hachimia" }, { nameAr: "الروراية", nameEn: "El Adjiba" }, { nameAr: "بن هارون", nameEn: "Ben Haroun" }, { nameAr: "دلس", nameEn: "Dechmia" }, { nameAr: "قادرية", nameEn: "Kadiria" }, { nameAr: "المعمورة", nameEn: "Maamora" }, { nameAr: "أولاد راشد", nameEn: "Ouled Rached" }, { nameAr: "الهاشمية", nameEn: "El Hachimia" }, { nameAr: "الروراية", nameEn: "El Adjiba" }, { nameAr: "بن هارون", nameEn: "Ben Haroun" }, { nameAr: "دلس", nameEn: "Dechmia" } ] },
  { code: "11", nameAr: "تمنراست", nameEn: "Tamanrasset", communes: [
    { nameAr: "تمنراست", nameEn: "Tamanrasset" }, { nameAr: "عين صالح", nameEn: "In Salah" }, { nameAr: "عين قزام", nameEn: "In Guezzam" }, { nameAr: "إديلس", nameEn: "Idles" }, { nameAr: "تاظروك", nameEn: "Tazrouk" }, { nameAr: "أبلسة", nameEn: "Abalessa" }, { nameAr: "تين زاوتين", nameEn: "Tin Zaouatine" } ] },
  { code: "12", nameAr: "تبسة", nameEn: "Tébessa", communes: [
    { nameAr: "تبسة", nameEn: "Tébessa" }, { nameAr: "الونزة", nameEn: "El Aouinet" }, { nameAr: "بئر العاتر", nameEn: "Bir El Ater" }, { nameAr: "الشريعة", nameEn: "Cheria" }, { nameAr: "العقلة", nameEn: "El Kouif" }, { nameAr: "الونزة", nameEn: "Morsott" }, { nameAr: "بئر العاتر", nameEn: "Bir El Ater" }, { nameAr: "تبسة", nameEn: "Tébessa" }, { nameAr: "الشريعة", nameEn: "Cheria" }, { nameAr: "العقلة", nameEn: "El Kouif" }, { nameAr: "الونزة", nameEn: "El Aouinet" }, { nameAr: "مورسوت", nameEn: "Morsott" }, { nameAr: "بكارية", nameEn: "Bekkaria" }, { nameAr: "بئر مقدم", nameEn: "Bir Mokadem" }, { nameAr: "الشريعة", nameEn: "Cheria" }, { nameAr: "الحمامات", nameEn: "El Hammamet" }, { nameAr: "العقلة المالحة", nameEn: "El Ogla" }, { nameAr: "الونزة", nameEn: "Négrine" }, { nameAr: "أم العظائم", nameEn: "Oum El Adhaim" }, { nameAr: "بكارية", nameEn: "Bekkaria" }, { nameAr: "بئر مقدم", nameEn: "Bir Mokadem" }, { nameAr: "الحمامات", nameEn: "El Hammamet" }, { nameAr: "العقلة المالحة", nameEn: "El Ogla" }, { nameAr: "الونزة", nameEn: "Négrine" }, { nameAr: "أم العظائم", nameEn: "Oum El Adhaim" }, { nameAr: "ساقية", nameEn: "Safsaf" }, { nameAr: "العقلة", nameEn: "El Kouif" } ] },
  { code: "13", nameAr: "تلمسان", nameEn: "Tlemcen", communes: [
    { nameAr: "تلمسان", nameEn: "Tlemcen" }, { nameAr: "ندرومة", nameEn: "Nedroma" }, { nameAr: "الغزوات", nameEn: "Ghazaouet" }, { nameAr: "مغنية", nameEn: "Maghnia" }, { nameAr: "الرمشي", nameEn: "Remchi" }, { nameAr: "السواحلية", nameEn: "Sebbaa" }, { nameAr: "شتوان", nameEn: "Chetouane" }, { nameAr: "السواحلية", nameEn: "Sebbaa" }, { nameAr: "الرمشي", nameEn: "Remchi" }, { nameAr: "مغنية", nameEn: "Maghnia" }, { nameAr: "تلمسان", nameEn: "Tlemcen" }, { nameAr: "ندرومة", nameEn: "Nedroma" }, { nameAr: "الغزوات", nameEn: "Ghazaouet" }, { nameAr: "بني سنوس", nameEn: "Beni Snous" }, { nameAr: "بني بهدل", nameEn: "Beni Bahdel" }, { nameAr: "بني خالد", nameEn: "Beni Khalled" }, { nameAr: "العمارية", nameEn: "El Aricha" }, { nameAr: "بني مهرات", nameEn: "Beni Mester" }, { nameAr: "عين تالوت", nameEn: "Aïn Tallout" }, { nameAr: "بني وارسون", nameEn: "Beni Ouarsous" }, { nameAr: "صبرة", nameEn: "Sabrah" }, { nameAr: "شتوان", nameEn: "Chetouane" }, { nameAr: "السواحلية", nameEn: "Sebbaa" }, { nameAr: "الرمشي", nameEn: "Remchi" }, { nameAr: "مغنية", nameEn: "Maghnia" }, { nameAr: "بني سنوس", nameEn: "Beni Snous" }, { nameAr: "بني بهدل", nameEn: "Beni Bahdel" }, { nameAr: "بني خالد", nameEn: "Beni Khalled" }, { nameAr: "العمارية", nameEn: "El Aricha" }, { nameAr: "بني مهرات", nameEn: "Beni Mester" }, { nameAr: "عين تالوت", nameEn: "Aïn Tallout" }, { nameAr: "بني وارسون", nameEn: "Beni Ouarsous" }, { nameAr: "صبرة", nameEn: "Sabrah" } ] },
  { code: "14", nameAr: "تيارت", nameEn: "Tiaret", communes: [
    { nameAr: "تيارت", nameEn: "Tiaret" }, { nameAr: "السوقر", nameEn: "Sougueur" }, { nameAr: "فرندة", nameEn: "Frenda" }, { nameAr: "مهدية", nameEn: "Mahdia" }, { nameAr: "عين الذهب", nameEn: "Ain Deheb" }, { nameAr: "تخمارت", nameEn: "Takdemt" }, { nameAr: "مهدية", nameEn: "Medrouna" }, { nameAr: "السوقر", nameEn: "Sougueur" }, { nameAr: "فرندة", nameEn: "Frenda" }, { nameAr: "تيارت", nameEn: "Tiaret" }, { nameAr: "عين الذهب", nameEn: "Ain Deheb" }, { nameAr: "تخمارت", nameEn: "Takdemt" }, { nameAr: "مهدية", nameEn: "Medrouna" }, { nameAr: "السوقر", nameEn: "Sougueur" }, { nameAr: "فرندة", nameEn: "Frenda" }, { nameAr: "مهدية", nameEn: "Mahdia" }, { nameAr: "عين الذهب", nameEn: "Ain Deheb" } ] },
  { code: "15", nameAr: "تيزي وزو", nameEn: "Tizi Ouzou", communes: [
    { nameAr: "تيزي وزو", nameEn: "Tizi Ouzou" }, { nameAr: "عزفون", nameEn: "Azefoun" }, { nameAr: "ذراع الميزان", nameEn: "Draa El Mizan" }, { nameAr: "بوغني", nameEn: "Boghni" }, { nameAr: "ماكودة", nameEn: "Makouda" }, { nameAr: "أزازقة", nameEn: "Azazga" }, { nameAr: "ميتي", nameEn: "Mekla" }, { nameAr: "ذراع بن خدة", nameEn: "Draâ Ben Khedda" }, { nameAr: "تيرميتين", nameEn: "Tirmirtine" }, { nameAr: "أزفون", nameEn: "Azefoun" }, { nameAr: "أزازقة", nameEn: "Azazga" }, { nameAr: "بوغني", nameEn: "Boghni" }, { nameAr: "ماكودة", nameEn: "Makouda" }, { nameAr: "ذراع الميزان", nameEn: "Draa El Mizan" }, { nameAr: "تيزي وزو", nameEn: "Tizi Ouzou" }, { nameAr: "ميتي", nameEn: "Mekla" }, { nameAr: "ذراع بن خدة", nameEn: "Draâ Ben Khedda" }, { nameAr: "تيرميتين", nameEn: "Tirmirtine" } ] },
  { code: "16", nameAr: "الجزائر", nameEn: "Alger", communes: [
    { nameAr: "الجزائر الوسطى", nameEn: "Alger Centre" }, { nameAr: "باب الوادي", nameEn: "Bab El Oued" }, { nameAr: "حسين داي", nameEn: "Hussein Dey" }, { nameAr: "المرادية", nameEn: "El Mouradia" }, { nameAr: "بئر مراد رايس", nameEn: "Bir Mourad Rais" }, { nameAr: "بوزريعة", nameEn: "Bouzareah" }, { nameAr: "الحراش", nameEn: "El Harrach" }, { nameAr: "دار البيضاء", nameEn: "Dar El Beida" }, { nameAr: "بئر خادم", nameEn: "Bir Khadem" }, { nameAr: "باب الزوار", nameEn: "Bab Ezzouar" }, { nameAr: "بن عكنون", nameEn: "Ben Aknoun" }, { nameAr: "حيدرة", nameEn: "Hydra" }, { nameAr: "القبة", nameEn: "El Biar" }, { nameAr: "بوزريعة", nameEn: "Bouzareah" }, { nameAr: "حسين داي", nameEn: "Hussein Dey" }, { nameAr: "المرادية", nameEn: "El Mouradia" }, { nameAr: "بئر مراد رايس", nameEn: "Bir Mourad Rais" }, { nameAr: "الحراش", nameEn: "El Harrach" }, { nameAr: "دار البيضاء", nameEn: "Dar El Beida" }, { nameAr: "بئر خادم", nameEn: "Bir Khadem" }, { nameAr: "بابة الزوار", nameEn: "Bab Ezzouar" }, { nameAr: "بن عكنون", nameEn: "Ben Aknoun" }, { nameAr: "حيدرة", nameEn: "Hydra" }, { nameAr: "القبة", nameEn: "El Biar" }, { nameAr: "دالي إبراهيم", nameEn: "Dely Ibrahim" }, { nameAr: "بوزريعة", nameEn: "Bouzareah" }, { nameAr: "الحراش", nameEn: "El Harrach" }, { nameAr: "دار البيضاء", nameEn: "Dar El Beida" }, { nameAr: "بئر خادم", nameEn: "Bir Khadem" }, { nameAr: "بابة الزوار", nameEn: "Bab Ezzouar" }, { nameAr: "بن عكنون", nameEn: "Ben Aknoun" }, { nameAr: "حيدرة", nameEn: "Hydra" }, { nameAr: "القبة", nameEn: "El Biar" }, { nameAr: "دالي إبراهيم", nameEn: "Dely Ibrahim" }, { nameAr: "زرالدة", nameEn: "Zeralda" }, { nameAr: "الشراقة", nameEn: "Cheraga" }, { nameAr: "عرافة", nameEn: "El Achour" }, { nameAr: "الرغاية", nameEn: "Rouiba" }, { nameAr: "الرغاية", nameEn: "Reghaia" }, { nameAr: "عين بنيان", nameEn: "Aïn Benian" }, { nameAr: "الشراقة", nameEn: "Cheraga" }, { nameAr: "دالي إبراهيم", nameEn: "Dely Ibrahim" }, { nameAr: "زرالدة", nameEn: "Zeralda" }, { nameAr: "الحراش", nameEn: "El Harrach" }, { nameAr: "دار البيضاء", nameEn: "Dar El Beida" } ] },
  { code: "17", nameAr: "الجلفة", nameEn: "Djelfa", communes: [
    { nameAr: "الجلفة", nameEn: "Djelfa" }, { nameAr: "عين وسارة", nameEn: "Aïn Oussera" }, { nameAr: "حاسي بحبح", nameEn: "Hassi Bahbah" }, { nameAr: "مسعد", nameEn: "Messaad" }, { nameAr: "الإدريسية", nameEn: "El Idrissia" }, { nameAr: "حاسي بحبح", nameEn: "Hassi Bahbah" }, { nameAr: "عين وسارة", nameEn: "Aïn Oussera" }, { nameAr: "الجلفة", nameEn: "Djelfa" }, { nameAr: "مسعد", nameEn: "Messaad" }, { nameAr: "الإدريسية", nameEn: "El Idrissia" }, { nameAr: "حاسي بحبح", nameEn: "Hassi Bahbah" }, { nameAr: "عين وسارة", nameEn: "Aïn Oussera" }, { nameAr: "الجلفة", nameEn: "Djelfa" }, { nameAr: "مسعد", nameEn: "Messaad" }, { nameAr: "الإدريسية", nameEn: "El Idrissia" } ] },
  { code: "18", nameAr: "جيجل", nameEn: "Jijel", communes: [
    { nameAr: "جيجل", nameEn: "Jijel" }, { nameAr: "الطاهير", nameEn: "El Taher" }, { nameAr: "الشحنة", nameEn: "Chekfa" }, { nameAr: "الميلية", nameEn: "Milia" }, { nameAr: "سيدي عبد العزيز", nameEn: "Sidi Abdelaziz" }, { nameAr: "العنصر", nameEn: "El Ancer" }, { nameAr: "الجمعة بني حبيبي", nameEn: "El Djemaa Beni Habibi" }, { nameAr: "سيدي عبد العزيز", nameEn: "Sidi Abdelaziz" }, { nameAr: "الميلية", nameEn: "Milia" }, { nameAr: "الشحنة", nameEn: "Chekfa" }, { nameAr: "الطاهير", nameEn: "El Taher" }, { nameAr: "جيجل", nameEn: "Jijel" }, { nameAr: "العنصر", nameEn: "El Ancer" }, { nameAr: "الجمعة بني حبيبي", nameEn: "El Djemaa Beni Habibi" } ] },
  { code: "19", nameAr: "سطيف", nameEn: "Sétif", communes: [
    { nameAr: "سطيف", nameEn: "Sétif" }, { nameAr: "العلمة", nameEn: "El Eulma" }, { nameAr: "عين ولمان", nameEn: "Aïn Oulmene" }, { nameAr: "بوقاعة", nameEn: "Bougaâ" }, { nameAr: "جميلة", nameEn: "Djémila" }, { nameAr: "عين أرنات", nameEn: "Aïn Arnat" }, { nameAr: "عين الكبيرة", nameEn: "Aïn El Kebira" }, { nameAr: "عين ولمان", nameEn: "Aïn Oulmene" }, { nameAr: "بوقاعة", nameEn: "Bougaâ" }, { nameAr: "جميلة", nameEn: "Djémila" }, { nameAr: "سطيف", nameEn: "Sétif" }, { nameAr: "العلمة", nameEn: "El Eulma" }, { nameAr: "عين أرنات", nameEn: "Aïn Arnat" }, { nameAr: "عين الكبيرة", nameEn: "Aïn El Kebira" }, { nameAr: "عين ولمان", nameEn: "Aïn Oulmene" }, { nameAr: "بوقاعة", nameEn: "Bougaâ" }, { nameAr: "جميلة", nameEn: "Djémila" }, { nameAr: "سطيف", nameEn: "Sétif" }, { nameAr: "العلمة", nameEn: "El Eulma" }, { nameAr: "عين أرنات", nameEn: "Aïn Arnat" }, { nameAr: "عين الكبيرة", nameEn: "Aïn El Kebira" } ] },
  { code: "20", nameAr: "سعيدة", nameEn: "Saïda", communes: [
    { nameAr: "سعيدة", nameEn: "Saïda" }, { nameAr: "عين الحجر", nameEn: "Aïn El Hadjar" }, { nameAr: "سيدي بوبكر", nameEn: "Sidi Boubekeur" }, { nameAr: "الدببة", nameEn: "El Hobba" }, { nameAr: "اليول", nameEn: "Youb" }, { nameAr: "عين الحجر", nameEn: "Aïn El Hadjar" }, { nameAr: "سيدي بوبكر", nameEn: "Sidi Boubekeur" }, { nameAr: "سعيدة", nameEn: "Saïda" }, { nameAr: "الدببة", nameEn: "El Hobba" }, { nameAr: "اليول", nameEn: "Youb" } ] },
  { code: "21", nameAr: "سكيكدة", nameEn: "Skikda", communes: [
    { nameAr: "سكيكدة", nameEn: "Skikda" }, { nameAr: "عزابة", nameEn: "Azzaba" }, { nameAr: "القل", nameEn: "Collo" }, { nameAr: "الحروش", nameEn: "El Harrouch" }, { nameAr: "تمالوس", nameEn: "Tamalous" }, { nameAr: "الزيتونة", nameEn: "El Hadaiek" }, { nameAr: "عزابة", nameEn: "Azzaba" }, { nameAr: "القل", nameEn: "Collo" }, { nameAr: "الحروش", nameEn: "El Harrouch" }, { nameAr: "سكيكدة", nameEn: "Skikda" }, { nameAr: "تمالوس", nameEn: "Tamalous" }, { nameAr: "الزيتونة", nameEn: "El Hadaiek" } ] },
  { code: "22", nameAr: "سيدي بلعباس", nameEn: "Sidi Bel Abbès", communes: [
    { nameAr: "سيدي بلعباس", nameEn: "Sidi Bel Abbès" }, { nameAr: "تلاغ", nameEn: "Telagh" }, { nameAr: "مرحوم", nameEn: "Merine" }, { nameAr: "بدرابين", nameEn: "Badrebine" }, { nameAr: "صفيزف", nameEn: "Sfisef" }, { nameAr: "تلاغ", nameEn: "Telagh" }, { nameAr: "مرحوم", nameEn: "Merine" }, { nameAr: "سيدي بلعباس", nameEn: "Sidi Bel Abbès" }, { nameAr: "بدرابين", nameEn: "Badrebine" }, { nameAr: "صفيزف", nameEn: "Sfisef" } ] },
  { code: "23", nameAr: "عنابة", nameEn: "Annaba", communes: [
    { nameAr: "عنابة", nameEn: "Annaba" }, { nameAr: "الحجار", nameEn: "El Hadjar" }, { nameAr: "البوني", nameEn: "Bouni" }, { nameAr: "سيدي عمار", nameEn: "Sidi Amar" }, { nameAr: "سرايدي", nameEn: "Seraïdi" }, { nameAr: "الحجار", nameEn: "El Hadjar" }, { nameAr: "البوني", nameEn: "Bouni" }, { nameAr: "عنابة", nameEn: "Annaba" }, { nameAr: "سيدي عمار", nameEn: "Sidi Amar" }, { nameAr: "سرايدي", nameEn: "Seraïdi" } ] },
  { code: "24", nameAr: "قالمة", nameEn: "Guelma", communes: [
    { nameAr: "قالمة", nameEn: "Guelma" }, { nameAr: "وادي الزناتي", nameEn: "Oued Zenati" }, { nameAr: "بومهرة أحمد", nameEn: "Boumahra Ahmed" }, { nameAr: "هيليوبوليس", nameEn: "Héliopolis" }, { nameAr: "حمام دباغ", nameEn: "Hammam Debagh" }, { nameAr: "وادي الزناتي", nameEn: "Oued Zenati" }, { nameAr: "بومهرة أحمد", nameEn: "Boumahra Ahmed" }, { nameAr: "قالمة", nameEn: "Guelma" }, { nameAr: "هيليوبوليس", nameEn: "Héliopolis" }, { nameAr: "حمام دباغ", nameEn: "Hammam Debagh" } ] },
  { code: "25", nameAr: "قسنطينة", nameEn: "Constantine", communes: [
    { nameAr: "قسنطينة", nameEn: "Constantine" }, { nameAr: "الخروب", nameEn: "El Khroub" }, { nameAr: "حامة بوزيان", nameEn: "Hamma Bouziane" }, { nameAr: "ديدوش مراد", nameEn: "Didouche Mourad" }, { nameAr: "زيغود يوسف", nameEn: "Zighoud Youcef" }, { nameAr: "الخروب", nameEn: "El Khroub" }, { nameAr: "حامة بوزيان", nameEn: "Hamma Bouziane" }, { nameAr: "قسنطينة", nameEn: "Constantine" }, { nameAr: "ديدوش مراد", nameEn: "Didouche Mourad" }, { nameAr: "زيغود يوسف", nameEn: "Zighoud Youcef" } ] },
  { code: "26", nameAr: "المدية", nameEn: "Médéa", communes: [
    { nameAr: "المدية", nameEn: "Médéa" }, { nameAr: "برج الكهف", nameEn: "Berrouaghia" }, { nameAr: "قصر البخاري", nameEn: "Ksar El Boukhari" }, { nameAr: "العمارية", nameEn: "El Omaria" }, { nameAr: "وزرة", nameEn: "Ouizer" }, { nameAr: "برج الكهف", nameEn: "Berrouaghia" }, { nameAr: "قصر البخاري", nameEn: "Ksar El Boukhari" }, { nameAr: "المدية", nameEn: "Médéa" }, { nameAr: "العمارية", nameEn: "El Omaria" }, { nameAr: "وزرة", nameEn: "Ouizer" } ] },
  { code: "27", nameAr: "مستغانم", nameEn: "Mostaganem", communes: [
    { nameAr: "مستغانم", nameEn: "Mostaganem" }, { nameAr: "عين تادلس", nameEn: "Aïn Tedles" }, { nameAr: "سيدي علي", nameEn: "Sidi Ali" }, { nameAr: "بوقيراط", nameEn: "Bouguirat" }, { nameAr: "حاسي ماماش", nameEn: "Hassi Mameche" }, { nameAr: "عين تادلس", nameEn: "Aïn Tedles" }, { nameAr: "سيدي علي", nameEn: "Sidi Ali" }, { nameAr: "مستغانم", nameEn: "Mostaganem" }, { nameAr: "بوقيراط", nameEn: "Bouguirat" }, { nameAr: "حاسي ماماش", nameEn: "Hassi Mameche" } ] },
  { code: "28", nameAr: "المسيلة", nameEn: "M'Sila", communes: [
    { nameAr: "المسيلة", nameEn: "M'Sila" }, { nameAr: "بوسعادة", nameEn: "Bou Saâda" }, { nameAr: "سيدي عيسى", nameEn: "Sidi Aïssa" }, { nameAr: "مقرة", nameEn: "Magra" }, { nameAr: "حمام الضلعة", nameEn: "Hammam Dhalaa" }, { nameAr: "بوسعادة", nameEn: "Bou Saâda" }, { nameAr: "سيدي عيسى", nameEn: "Sidi Aïssa" }, { nameAr: "المسيلة", nameEn: "M'Sila" }, { nameAr: "مقرة", nameEn: "Magra" }, { nameAr: "حمام الضلعة", nameEn: "Hammam Dhalaa" } ] },
  { code: "29", nameAr: "معسكر", nameEn: "Mascara", communes: [
    { nameAr: "معسكر", nameEn: "Mascara" }, { nameAr: "غريس", nameEn: "Ghriss" }, { nameAr: "تيغنيف", nameEn: "Tighennif" }, { nameAr: "وهران", nameEn: "El Hachem" }, { nameAr: "سيق", nameEn: "Sig" }, { nameAr: "غريس", nameEn: "Ghriss" }, { nameAr: "تيغنيف", nameEn: "Tighennif" }, { nameAr: "معسكر", nameEn: "Mascara" }, { nameAr: "وهران", nameEn: "El Hachem" }, { nameAr: "سيق", nameEn: "Sig" } ] },
  { code: "30", nameAr: "ورقلة", nameEn: "Ouargla", communes: [
    { nameAr: "ورقلة", nameEn: "Ouargla" }, { nameAr: "تقرت", nameEn: "Touggourt" }, { nameAr: "حاسي مسعود", nameEn: "Hassi Messaoud" }, { nameAr: "النزلة", nameEn: "N'Goussa" }, { nameAr: "عين البيضاء", nameEn: "Rouissat" }, { nameAr: "الرويسات", nameEn: "Rouissat" }, { nameAr: "حاسي مسعود", nameEn: "Hassi Messaoud" }, { nameAr: "ورقلة", nameEn: "Ouargla" }, { nameAr: "النزلة", nameEn: "N'Goussa" }, { nameAr: "سيدي خويلد", nameEn: "Sidi Khouiled" } ] },
  { code: "31", nameAr: "وهران", nameEn: "Oran", communes: [
    { nameAr: "وهران", nameEn: "Oran" }, { nameAr: "بئر الجير", nameEn: "Bir El Djir" }, { nameAr: "السانية", nameEn: "Es Senia" }, { nameAr: "عين التركي", nameEn: "Aïn El Turk" }, { nameAr: "أرزيو", nameEn: "Arzew" }, { nameAr: "بطيوة", nameEn: "Bethioua" }, { nameAr: "السانية", nameEn: "Es Senia" }, { nameAr: "عين التركي", nameEn: "Aïn El Turk" }, { nameAr: "وهران", nameEn: "Oran" }, { nameAr: "أرزيو", nameEn: "Arzew" }, { nameAr: "بطيوة", nameEn: "Bethioua" }, { nameAr: "بئر الجير", nameEn: "Bir El Djir" }, { nameAr: "السانية", nameEn: "Es Senia" }, { nameAr: "عين التركي", nameEn: "Aïn El Turk" } ] },
  { code: "32", nameAr: "البيض", nameEn: "El Bayadh", communes: [
    { nameAr: "البيض", nameEn: "El Bayadh" }, { nameAr: "الأبيض سيدي الشيخ", nameEn: "Bougtoub" }, { nameAr: "بريزينة", nameEn: "Brezina" }, { nameAr: "بوقطب", nameEn: "El Abiodh Sidi Cheikh" }, { nameAr: "كرارة", nameEn: "Kerrara" }, { nameAr: "الأبيض سيدي الشيخ", nameEn: "Bougtoub" }, { nameAr: "بريزينة", nameEn: "Brezina" }, { nameAr: "البيض", nameEn: "El Bayadh" }, { nameAr: "بوقطب", nameEn: "El Abiodh Sidi Cheikh" }, { nameAr: "كرارة", nameEn: "Kerrara" } ] },
  { code: "33", nameAr: "إليزي", nameEn: "Illizi", communes: [
    { nameAr: "إليزي", nameEn: "Illizi" }, { nameAr: "جانت", nameEn: "Djanet" }, { nameAr: "برج عمر إدريس", nameEn: "Bordj Omar Driss" }, { nameAr: "إن أمناس", nameEn: "In Amenas" }, { nameAr: "برج الحواس", nameEn: "Bordj El Haouas" } ] },
  { code: "34", nameAr: "برج بوعريريج", nameEn: "Bordj Bou Arréridj", communes: [
    { nameAr: "برج بوعريريج", nameEn: "Bordj Bou Arréridj" }, { nameAr: "رأس الوادي", nameEn: "Ras El Oued" }, { nameAr: "مجانة", nameEn: "Mansoura" }, { nameAr: "الحمادية", nameEn: "El Hamadia" }, { nameAr: "بئر قاصد علي", nameEn: "Bir Kasd Ali" }, { nameAr: "رأس الوادي", nameEn: "Ras El Oued" }, { nameAr: "مجانة", nameEn: "Mansoura" }, { nameAr: "برج بوعريريج", nameEn: "Bordj Bou Arréridj" }, { nameAr: "الحمادية", nameEn: "El Hamadia" }, { nameAr: "بئر قاصد علي", nameEn: "Bir Kasd Ali" } ] },
  { code: "35", nameAr: "بومرداس", nameEn: "Boumerdès", communes: [
    { nameAr: "بومرداس", nameEn: "Boumerdès" }, { nameAr: "بودواو", nameEn: "Boudouaou" }, { nameAr: "الناصرية", nameEn: "Bordj Menaiel" }, { nameAr: "خميس الخشنة", nameEn: "Khemis El Khechna" }, { nameAr: "أولاد موسى", nameEn: "Ouled Moussa" }, { nameAr: "بودواو", nameEn: "Boudouaou" }, { nameAr: "الناصرية", nameEn: "Bordj Menaiel" }, { nameAr: "بومرداس", nameEn: "Boumerdès" }, { nameAr: "خميس الخشنة", nameEn: "Khemis El Khechna" }, { nameAr: "أولاد موسى", nameEn: "Ouled Moussa" } ] },
  { code: "36", nameAr: "الطارف", nameEn: "El Tarf", communes: [
    { nameAr: "الطارف", nameEn: "El Tarf" }, { nameAr: "القالة", nameEn: "El Kala" }, { nameAr: "بن مهيدي", nameEn: "Ben M'Hidi" }, { nameAr: "بوحجار", nameEn: "Bouhadjar" }, { nameAr: "الذرعان", nameEn: "Drean" }, { nameAr: "القالة", nameEn: "El Kala" }, { nameAr: "بن مهيدي", nameEn: "Ben M'Hidi" }, { nameAr: "الطارف", nameEn: "El Tarf" }, { nameAr: "بوحجار", nameEn: "Bouhadjar" }, { nameAr: "الذرعان", nameEn: "Drean" } ] },
  { code: "37", nameAr: "تندوف", nameEn: "Tindouf", communes: [
    { nameAr: "تندوف", nameEn: "Tindouf" }, { nameAr: "أم العسل", nameEn: "Oum El Assel" } ] },
  { code: "38", nameAr: "تيسمسيلت", nameEn: "Tissemsilt", communes: [
    { nameAr: "تيسمسيلت", nameEn: "Tissemsilt" }, { nameAr: "ثنية الحد", nameEn: "Theniet El Had" }, { nameAr: "بوقايد", nameEn: "Bordj Bou Naama" }, { nameAr: "لرجام", nameEn: "Lardjem" }, { nameAr: "بني شعيب", nameEn: "Bordi Chaabat" }, { nameAr: "ثنية الحد", nameEn: "Theniet El Had" }, { nameAr: "بوقايد", nameEn: "Bordj Bou Naama" }, { nameAr: "تيسمسيلت", nameEn: "Tissemsilt" }, { nameAr: "لرجام", nameEn: "Lardjem" }, { nameAr: "بني شعيب", nameEn: "Bordi Chaabat" } ] },
  { code: "39", nameAr: "الوادي", nameEn: "El Oued", communes: [
    { nameAr: "الوادي", nameEn: "El Oued" }, { nameAr: "قمار", nameEn: "Guemar" }, { nameAr: "البياضة", nameEn: "Robbah" }, { nameAr: "النخلة", nameEn: "Debila" }, { nameAr: "الجامعة", nameEn: "Djamaa" }, { nameAr: "قمار", nameEn: "Guemar" }, { nameAr: "البياضة", nameEn: "Robbah" }, { nameAr: "الوادي", nameEn: "El Oued" }, { nameAr: "النخلة", nameEn: "Debila" }, { nameAr: "الجامعة", nameEn: "Djamaa" }, { nameAr: "القصيدة", nameEn: "El Ogla" }, { nameAr: "باورة", nameEn: "Bayadha" }, { nameAr: "المحيريق", nameEn: "Magrane" }, { nameAr: "تغزوت", nameEn: "Taghzout" }, { nameAr: "وادي العلندة", nameEn: "Oued El Alenda" } ] },
  { code: "40", nameAr: "خنشلة", nameEn: "Khenchela", communes: [
    { nameAr: "خنشلة", nameEn: "Khenchela" }, { nameAr: "بابار", nameEn: "Babar" }, { nameAr: "شليا", nameEn: "Chechar" }, { nameAr: "كايس", nameEn: "Kais" }, { nameAr: "تاوزيانت", nameEn: "Taouzianat" }, { nameAr: "بابار", nameEn: "Babar" }, { nameAr: "شليا", nameEn: "Chechar" }, { nameAr: "خنشلة", nameEn: "Khenchela" }, { nameAr: "كايس", nameEn: "Kais" }, { nameAr: "تاوزيانت", nameEn: "Taouzianat" } ] },
  { code: "41", nameAr: "سوق أهراس", nameEn: "Souk Ahras", communes: [
    { nameAr: "سوق أهراس", nameEn: "Souk Ahras" }, { nameAr: "مداوروش", nameEn: "M'Daourouch" }, { nameAr: "تاورة", nameEn: "Taoura" }, { nameAr: "الحدادة", nameEn: "Heddada" }, { nameAr: "أم العظائم", nameEn: "Oum El Adhaim" }, { nameAr: "مداوروش", nameEn: "M'Daourouch" }, { nameAr: "تاورة", nameEn: "Taoura" }, { nameAr: "سوق أهراس", nameEn: "Souk Ahras" }, { nameAr: "الحدادة", nameEn: "Heddada" }, { nameAr: "أم العظائم", nameEn: "Oum El Adhaim" } ] },
  { code: "42", nameAr: "تيبازة", nameEn: "Tipaza", communes: [
    { nameAr: "تيبازة", nameEn: "Tipaza" }, { nameAr: "حجوط", nameEn: "Hadjout" }, { nameAr: "الخميست", nameEn: "Khemisti" }, { nameAr: "شرشال", nameEn: "Cherchell" }, { nameAr: "دوار", nameEn: "Douaouda" }, { nameAr: "حجوط", nameEn: "Hadjout" }, { nameAr: "الخميست", nameEn: "Khemisti" }, { nameAr: "تيبازة", nameEn: "Tipaza" }, { nameAr: "شرشال", nameEn: "Cherchell" }, { nameAr: "دوار", nameEn: "Douaouda" } ] },
  { code: "43", nameAr: "ميلة", nameEn: "Mila", communes: [
    { nameAr: "ميلة", nameEn: "Mila" }, { nameAr: "فرجيوة", nameEn: "Ferdjioua" }, { nameAr: "شلغوم العيد", nameEn: "Chelghoum Laïd" }, { nameAr: "وادي العثمانية", nameEn: "Oued Athmenia" }, { nameAr: "تاجنانت", nameEn: "Tadjenanet" }, { nameAr: "فرجيوة", nameEn: "Ferdjioua" }, { nameAr: "شلغوم العيد", nameEn: "Chelghoum Laïd" }, { nameAr: "ميلة", nameEn: "Mila" }, { nameAr: "وادي العثمانية", nameEn: "Oued Athmenia" }, { nameAr: "تاجنانت", nameEn: "Tadjenanet" } ] },
  { code: "44", nameAr: "عين الدفلى", nameEn: "Aïn Defla", communes: [
    { nameAr: "عين الدفلى", nameEn: "Aïn Defla" }, { nameAr: "خميس مليانة", nameEn: "Khemis Miliana" }, { nameAr: "العامرة", nameEn: "El Amra" }, { nameAr: "بوراشد", nameEn: "Bourached" }, { nameAr: "العطاف", nameEn: "El Attaf" }, { nameAr: "خميس مليانة", nameEn: "Khemis Miliana" }, { nameAr: "العامرة", nameEn: "El Amra" }, { nameAr: "عين الدفلى", nameEn: "Aïn Defla" }, { nameAr: "بوراشد", nameEn: "Bourached" }, { nameAr: "العطاف", nameEn: "El Attaf" } ] },
  { code: "45", nameAr: "النعامة", nameEn: "Naâma", communes: [
    { nameAr: "النعامة", nameEn: "Naâma" }, { nameAr: "المشرية", nameEn: "Mecheria" }, { nameAr: "عين الصفراء", nameEn: "Aïn Sefra" }, { nameAr: "صفيصيفة", nameEn: "Sfissifa" }, { nameAr: "تيوت", nameEn: "Tiout" }, { nameAr: "المشرية", nameEn: "Mecheria" }, { nameAr: "عين الصفراء", nameEn: "Aïn Sefra" }, { nameAr: "النعامة", nameEn: "Naâma" }, { nameAr: "صفيصيفة", nameEn: "Sfissifa" }, { nameAr: "تيوت", nameEn: "Tiout" } ] },
  { code: "46", nameAr: "عين تموشنت", nameEn: "Aïn Témouchent", communes: [
    { nameAr: "عين تموشنت", nameEn: "Aïn Témouchent" }, { nameAr: "الحمام", nameEn: "El Hammam" }, { nameAr: "وادي الصباح", nameEn: "Oued Sabah" }, { nameAr: "الإمام رفيعة", nameEn: "Ain Kihal" }, { nameAr: "تامزورة", nameEn: "Tamzoura" }, { nameAr: "الحمام", nameEn: "El Hammam" }, { nameAr: "وادي الصباح", nameEn: "Oued Sabah" }, { nameAr: "عين تموشنت", nameEn: "Aïn Témouchent" }, { nameAr: "الإمام رفيعة", nameEn: "Ain Kihal" }, { nameAr: "تامزورة", nameEn: "Tamzoura" } ] },
  { code: "47", nameAr: "غرداية", nameEn: "Ghardaïa", communes: [
    { nameAr: "غرداية", nameEn: "Ghardaïa" }, { nameAr: "متليلي", nameEn: "Metlili" }, { nameAr: "بريان", nameEn: "Berriane" }, { nameAr: "ضاية بن ضحوة", nameEn: "Daya Ben Dahoua" }, { nameAr: "الضيعة", nameEn: "El Guerrara" }, { nameAr: "متليلي", nameEn: "Metlili" }, { nameAr: "بريان", nameEn: "Berriane" }, { nameAr: "غرداية", nameEn: "Ghardaïa" }, { nameAr: "ضاية بن ضحوة", nameEn: "Daya Ben Dahoua" }, { nameAr: "الضيعة", nameEn: "El Guerrara" }, { nameAr: "العطف", nameEn: "El Atteuf" }, { nameAr: "سبت", nameEn: "Sebseb" }, { nameAr: "زلفانة", nameEn: "Zelfana" }, { nameAr: "بونورة", nameEn: "Bounoura" }, { nameAr: "حاسي القارة", nameEn: "Hassi El Gara" } ] },
  { code: "48", nameAr: "غليزان", nameEn: "Relizane", communes: [
    { nameAr: "غليزان", nameEn: "Relizane" }, { nameAr: "مازونة", nameEn: "Mazouna" }, { nameAr: "عمي موسى", nameEn: "Ammi Moussa" }, { nameAr: "وادي رهيو", nameEn: "Oued Rhiou" }, { nameAr: "بئر الدباغ", nameEn: "Belaa" }, { nameAr: "مازونة", nameEn: "Mazouna" }, { nameAr: "عمي موسى", nameEn: "Ammi Moussa" }, { nameAr: "غليزان", nameEn: "Relizane" }, { nameAr: "وادي رهيو", nameEn: "Oued Rhiou" }, { nameAr: "بئر الدباغ", nameEn: "Belaa" } ] },
  { code: "49", nameAr: "المغير", nameEn: "El M'Ghair", communes: [
    { nameAr: "المغير", nameEn: "El M'Ghair" }, { nameAr: "أم الطيور", nameEn: "Oum Touyour" }, { nameAr: "سيدي خليل", nameEn: "Sidi Khelifa" }, { nameAr: "ستيل", nameEn: "Still" }, { nameAr: "تنديلة", nameEn: "Tendla" }, { nameAr: "جامعة", nameEn: "Djamaa" }, { nameAr: "المقرن", nameEn: "M'Rara" }, { nameAr: "سيدي عمران", nameEn: "Sidi Amrane" }, { nameAr: "أولاد الرشم", nameEn: "Ouled Rachem" }, { nameAr: "الرقيبة", nameEn: "Sidi Khellil" } ] },
  { code: "50", nameAr: "المنيعة", nameEn: "El Meniaa", communes: [
    { nameAr: "المنيعة", nameEn: "El Meniaa" }, { nameAr: "حاسي القارة", nameEn: "Hassi Gara" }, { nameAr: "حاسي الفحل", nameEn: "Hassi El Fhal" } ] },
  { code: "51", nameAr: "أولاد جلال", nameEn: "Ouled Djellal", communes: [
    { nameAr: "أولاد جلال", nameEn: "Ouled Djellal" }, { nameAr: "سيدي خالد", nameEn: "Sidi Khaled" }, { nameAr: "الدوسن", nameEn: "Doucen" }, { nameAr: "الشعيبة", nameEn: "Chaiba" }, { nameAr: "السبع", nameEn: "Sidi Laadjal" } ] },
  { code: "52", nameAr: "برج باجي مختار", nameEn: "Bordj Baji Mokhtar", communes: [
    { nameAr: "برج باجي مختار", nameEn: "Bordj Baji Mokhtar" }, { nameAr: "تيمياوين", nameEn: "Timiaouine" } ] },
  { code: "53", nameAr: "بني عبس", nameEn: "Béni Abbès", communes: [
    { nameAr: "بني عبس", nameEn: "Béni Abbès" }, { nameAr: "تابلبالة", nameEn: "Tabelbala" }, { nameAr: "إقلي", nameEn: "Igli" }, { nameAr: "كرزاز", nameEn: "Kerzaz" }, { nameAr: "تاترت", nameEn: "Tatarent" }, { nameAr: "بوقطب", nameEn: "El Ouata" } ] },
  { code: "54", nameAr: "تيميمون", nameEn: "Timimoun", communes: [
    { nameAr: "تيميمون", nameEn: "Timimoun" }, { nameAr: "أوقروت", nameEn: "Ouled Said" }, { nameAr: "شروين", nameEn: "Charouine" }, { nameAr: "تينركوك", nameEn: "Tinerkouk" }, { nameAr: "أولاد سعيد", nameEn: "Aougrout" }, { nameAr: "دلدول", nameEn: "Deldoul" }, { nameAr: "المقاربة", nameEn: "Metarfa" }, { nameAr: "تسابيت", nameEn: "Tsabit" }, { nameAr: "قاوة", nameEn: "Ksar Kaddour" } ] },
  { code: "55", nameAr: "تقرت", nameEn: "Touggourt", communes: [
    { nameAr: "تقرت", nameEn: "Touggourt" }, { nameAr: "المقارعة", nameEn: "Megarine" }, { nameAr: "الطيبات", nameEn: "Tebesbest" }, { nameAr: "العقلة المالحة", nameEn: "El Hadjira" }, { nameAr: "زعطوط", nameEn: "Zaouia El Abidia" }, { nameAr: "تماسين", nameEn: "Tamacine" }, { nameAr: "بلدة عمر", nameEn: "Balidat Ameur" }, { nameAr: "بنقشة", nameEn: "Benaceur" }, { nameAr: "المقارنة", nameEn: "M'Rara" }, { nameAr: "سيدي سليمان", nameEn: "Sidi Slimane" }, { nameAr: "الطيبات", nameEn: "Nezla" } ] },
  { code: "56", nameAr: "جانت", nameEn: "Djanet", communes: [
    { nameAr: "جانت", nameEn: "Djanet" }, { nameAr: "برج الحواس", nameEn: "Bordj El Haouas" } ] },
  { code: "57", nameAr: "عين صالح", nameEn: "In Salah", communes: [
    { nameAr: "عين صالح", nameEn: "In Salah" }, { nameAr: "فقارة الزوى", nameEn: "Foggaret Ezzoua" }, { nameAr: "إقلي", nameEn: "In Ghar" } ] },
  { code: "58", nameAr: "عين قزام", nameEn: "In Guezzam", communes: [
    { nameAr: "عين قزام", nameEn: "In Guezzam" }, { nameAr: "تين زواتين", nameEn: "Tin Zaouatine" } ] },
];
